- name: Instalar e configurar Zabbix Agent 2 em máquinas Ubuntu
  hosts: all
  become: true
  gather_facts: true

  vars:
    zabbix_server_ip: "192.168.10.202"  # IP do seu servidor Zabbix
    zabbix_agent_version: "7.0"
    # Usamos o nome da máquina detectado pelo Ansible
    zabbix_hostname: "{{ ansible_hostname }}"
    # Metadata "Linux" para ativar sua regra de Auto Registration
    zabbix_host_metadata: "Linux"

  tasks:

    # 1. SEGURANÇA: Garante que o agente antigo não atrapalhe a porta 10050
    - name: Parar e desabilitar Zabbix Agent antigo (se existir)
      service:
        name: zabbix-agent
        state: stopped
        enabled: no
      ignore_errors: yes  # Ignora erro se o agente antigo nunca foi instalado

    - name: Limpar cache APT
      apt:
        clean: yes

    - name: Remover qualquer .deb antigo ou corrompido
      file:
        path: /tmp/zabbix-release.deb
        state: absent

    - name: Instalar pré-requisitos
      apt:
        name:
          - wget
          - gnupg
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Baixar pacote do repositório Zabbix (Debian/Ubuntu)
      command: >
          wget "https://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_agent_version }}-1+ubuntu{{ ansible_distribution_version }}_all.deb" -O /tmp/zabbix-release.deb
      args:
        creates: /tmp/zabbix-release.deb

    - name: Instalar repositório Zabbix
      apt:
        deb: /tmp/zabbix-release.deb
        state: present
        update_cache: yes

    # 2. INSTALAÇÃO: Mudança do nome do pacote para zabbix-agent2
    - name: Instalar Zabbix Agent 2
      apt:
        name: zabbix-agent2
        state: latest
        update_cache: yes
      register: install_agent

    - name: Recarregar unidades systemd
      systemd:
        daemon_reload: yes
      when: install_agent.changed

    # 3. CONFIGURAÇÃO: Editando o arquivo correto (/etc/zabbix/zabbix_agent2.conf)
    - name: Configurar zabbix_agent2.conf
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^Server=',       line: "Server={{ zabbix_server_ip }}" }
        - { regexp: '^ServerActive=', line: "ServerActive={{ zabbix_server_ip }}" }
        - { regexp: '^Hostname=',     line: "Hostname={{ zabbix_hostname }}" }
        # Adiciona o Metadata no final se não existir (necessário para seu Auto Discovery)
        - { regexp: '^HostMetadata=', line: "HostMetadata={{ zabbix_host_metadata }}" }

    # 4. REINÍCIO: Serviço correto zabbix-agent2
    - name: Reiniciar e habilitar Zabbix Agent 2
      service:
        name: zabbix-agent2
        state: restarted
        enabled: yes